/* Process model C form file: ertms_mobility.pr.c */
/* Portions of this file copyright 1986-2012 by OPNET Technologies, Inc. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from ertms_mobility.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char ertms_mobility_pr_c [] = "MIL_3_Tfile_Hdr_ 171A 30A op_mksim 7 52FCC1D4 52FCC1D4 1 siegel florent 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 2b74 2                                                                                                                                                                                                                                                                                                                                                                                                          ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */



#include "stdlib.h"
#include "stdio.h"
#include "string.h"

#define STRM (op_intrpt_type () == OPC_INTRPT_STRM)
#define ESYS (op_intrpt_type () == OPC_INTRPT_ESYS_INTERFACE)

#define min(X, Y)  ((X) < (Y) ? (X) : (Y))

#define MAX_NB_TRAIN 10

typedef struct _Ertms_Train_Pos{
	char name[256];
	double posx;
	double posy;
}Ertms_Train_Pos;


/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
typedef struct
	{
	/* Internal state tracking for FSM */
	FSM_SYS_STATE
	/* State Variables */
	Esys_Interface	         		inf_nb_train                                    ;
	Esys_Interface	         		inf_test                                        ;
	Objid	                  		net_id                                          ;
	} ertms_mobility_state;

#define inf_nb_train            		op_sv_ptr->inf_nb_train
#define inf_test                		op_sv_ptr->inf_test
#define net_id                  		op_sv_ptr->net_id

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	ertms_mobility_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((ertms_mobility_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ + 2};
#endif

void printTrainPos(const Ertms_Train_Pos* train_pos){
	printf("\tPosition of %s : %f,%f\n",train_pos->name, train_pos->posx,train_pos->posy);
}

void showNodePos(const Objid node_objid){
	double x,y;
	op_ima_obj_attr_get_dbl (node_objid, "x position", &x);
	op_ima_obj_attr_get_dbl (node_objid, "y position", &y);
	printf("\tOld Position %f %f\n",x,y);
}

/* End of Function Block */

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

#if defined (__cplusplus)
extern "C" {
#endif
	void ertms_mobility (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Obtype _op_ertms_mobility_init (int * init_block_ptr);
	void _op_ertms_mobility_diag (OP_SIM_CONTEXT_ARG_OPT);
	void _op_ertms_mobility_terminate (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Address _op_ertms_mobility_alloc (VosT_Obtype, int);
	void _op_ertms_mobility_svar (void *, const char *, void **);


#if defined (__cplusplus)
} /* end of 'extern "C"' */
#endif




/* Process model interrupt handling procedure */


void
ertms_mobility (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (ertms_mobility ());

		{
		/* Temporary Variables */
		int nb_train;
		Ertms_Train_Pos *train_pos;
		/* End of Temporary Variables */


		FSM_ENTER ("ertms_mobility")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (init) enter executives **/
			FSM_STATE_ENTER_FORCED_NOLABEL (0, "init", "ertms_mobility [init enter execs]")
				FSM_PROFILE_SECTION_IN ("ertms_mobility [init enter execs]", state0_enter_exec)
				{
				
				inf_nb_train = op_id_from_name(
					op_id_self(), OPC_OBJTYPE_ESINTERFACE, "nb_train");
				
				inf_test = op_id_from_name(
					op_id_self(), OPC_OBJTYPE_ESINTERFACE, "train_pos");
				
				net_id=op_topo_parent(op_topo_parent(op_id_self ()));
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** state (init) exit executives **/
			FSM_STATE_EXIT_FORCED (0, "init", "ertms_mobility [init exit execs]")


			/** state (init) transition processing **/
			FSM_TRANSIT_FORCE (1, state1_enter_exec, ;, "default", "", "init", "idle", "tr_4", "ertms_mobility [init -> idle : default / ]")
				/*---------------------------------------------------------*/



			/** state (idle) enter executives **/
			FSM_STATE_ENTER_UNFORCED (1, "idle", state1_enter_exec, "ertms_mobility [idle enter execs]")

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (3,"ertms_mobility")


			/** state (idle) exit executives **/
			FSM_STATE_EXIT_UNFORCED (1, "idle", "ertms_mobility [idle exit execs]")


			/** state (idle) transition processing **/
			FSM_PROFILE_SECTION_IN ("ertms_mobility [idle trans conditions]", state1_trans_conds)
			FSM_INIT_COND (ESYS)
			FSM_DFLT_COND
			FSM_TEST_LOGIC ("idle")
			FSM_PROFILE_SECTION_OUT (state1_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 2, state2_enter_exec, ;, "ESYS", "", "idle", "esys", "tr_8", "ertms_mobility [idle -> esys : ESYS / ]")
				FSM_CASE_TRANSIT (1, 1, state1_enter_exec, ;, "default", "", "idle", "idle", "tr_11", "ertms_mobility [idle -> idle : default / ]")
				}
				/*---------------------------------------------------------*/



			/** state (esys) enter executives **/
			FSM_STATE_ENTER_UNFORCED (2, "esys", state2_enter_exec, "ertms_mobility [esys enter execs]")
				FSM_PROFILE_SECTION_IN ("ertms_mobility [esys enter execs]", state2_enter_exec)
				{
				
				train_pos = (Ertms_Train_Pos*) op_prg_mem_alloc (sizeof (Ertms_Train_Pos) * MAX_NB_TRAIN);
				
				op_esys_interface_value_get(inf_nb_train, &nb_train, 0);
				op_esys_interface_value_get(inf_test, &train_pos, 0);
				
				printf("Positions %d\n",nb_train);
				
				const int nb = min(nb_train,MAX_NB_TRAIN);
				for(int i=0;i<nb;i++) {
					const Objid node_objid=op_id_from_name (net_id, OPC_OBJTYPE_NODE_MOB, train_pos[i].name);
					printTrainPos(train_pos+i);
					showNodePos(node_objid);
					op_ima_obj_attr_set_dbl (node_objid, "x position", train_pos[i].posx);
					op_ima_obj_attr_set_dbl (node_objid, "y position", train_pos[i].posy);
				}
				
				op_prg_mem_free(train_pos);
				
				}
				FSM_PROFILE_SECTION_OUT (state2_enter_exec)

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (5,"ertms_mobility")


			/** state (esys) exit executives **/
			FSM_STATE_EXIT_UNFORCED (2, "esys", "ertms_mobility [esys exit execs]")


			/** state (esys) transition processing **/
			FSM_TRANSIT_FORCE (1, state1_enter_exec, ;, "default", "", "esys", "idle", "tr_9", "ertms_mobility [esys -> idle : default / ]")
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"ertms_mobility")
		}
	}




void
_op_ertms_mobility_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}




void
_op_ertms_mobility_terminate (OP_SIM_CONTEXT_ARG_OPT)
	{

	FIN_MT (_op_ertms_mobility_terminate ())


	/* No Termination Block */

	Vos_Poolmem_Dealloc (op_sv_ptr);

	FOUT
	}


/* Undefine shortcuts to state variables to avoid */
/* syntax error in direct access to fields of */
/* local variable prs_ptr in _op_ertms_mobility_svar function. */
#undef inf_nb_train
#undef inf_test
#undef net_id

#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

VosT_Obtype
_op_ertms_mobility_init (int * init_block_ptr)
	{
	VosT_Obtype obtype = OPC_NIL;
	FIN_MT (_op_ertms_mobility_init (init_block_ptr))

	obtype = Vos_Define_Object_Prstate ("proc state vars (ertms_mobility)",
		sizeof (ertms_mobility_state));
	*init_block_ptr = 0;

	FRET (obtype)
	}

VosT_Address
_op_ertms_mobility_alloc (VosT_Obtype obtype, int init_block)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	ertms_mobility_state * ptr;
	FIN_MT (_op_ertms_mobility_alloc (obtype))

	ptr = (ertms_mobility_state *)Vos_Alloc_Object (obtype);
	if (ptr != OPC_NIL)
		{
		ptr->_op_current_block = init_block;
#if defined (OPD_ALLOW_ODB)
		ptr->_op_current_state = "ertms_mobility [init enter execs]";
#endif
		}
	FRET ((VosT_Address)ptr)
	}



void
_op_ertms_mobility_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	ertms_mobility_state		*prs_ptr;

	FIN_MT (_op_ertms_mobility_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (ertms_mobility_state *)gen_ptr;

	if (strcmp ("inf_nb_train" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->inf_nb_train);
		FOUT
		}
	if (strcmp ("inf_test" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->inf_test);
		FOUT
		}
	if (strcmp ("net_id" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->net_id);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

